MODEL:
  TYPE: FlowChain_CIF_separate_cond
  ENCODER_TYPE: trajectron
  FLOW:
    ARCHITECTURE: MAF

DATA:
  DATASET_NAME: "simfork"
  TRAJ:
    PRED_STATE: 'state_v'
    ACCEPT_NAN: False

SOLVER:
  USE_SCHEDULER: True
  WEIGHT_DECAY: 0.0