MODEL:
  TYPE: fastpredNF_separate_cond
  ENCODER_TYPE: trajectron

DATA:
  DATASET_NAME: "simfork"
  TP:
    PRED_STATE: 'state_v'
    ACCEPT_NAN: False

SOLVER:
  USE_SCHEDULER: True
  WEIGHT_DECAY: 0.0