MODEL:
  TYPE: fastpredNF_CIF_separate
  ENCODER_TYPE: trajectron
  FLOW:
    ARCHITECTURE: MAF

DATA:
  DATASET_NAME: "univ"
  TP:
    PRED_STATE: 'state_v'
    ACCEPT_NAN: True
    
SOLVER:
  USE_SCHEDULER: True
  WEIGHT_DECAY: 0.0