MODEL:
  TYPE: FlowChain_separate
  ENCODER_TYPE: trajectron

DATA:
  DATASET_NAME: "zara1"
  TRAJ:
    PRED_STATE: 'state_v'
    ACCEPT_NAN: True
    
SOLVER:
  USE_SCHEDULER: True
  WEIGHT_DECAY: 0.0