MODEL:
  TYPE: FlowChain_CIF_separate_cond
  ENCODER_TYPE: trajectron

DATA:
  DATASET_NAME: "simfork"
  PREDICT_LENGTH: 11
  OBSERVE_LENGTH: 9
  TRAJ:
    PRED_STATE: 'state_v'
    ACCEPT_NAN: False
    
SOLVER:
  USE_SCHEDULER: True
  WEIGHT_DECAY: 0.0
  ITER: 500
  