MODEL:
  TYPE: FlowChain_CIF_separate_cond
  ENCODER_TYPE: trajectron

DATA:
  DATASET_NAME: "simfork_longer5"
  PREDICT_LENGTH: 17
  TRAJ:
    PRED_STATE: 'state_v'
    ACCEPT_NAN: False
    
SOLVER:
  USE_SCHEDULER: True
  WEIGHT_DECAY: 0.0
  ITER: 500
  