MODEL:
  TYPE: FlowChain_CIF_separate_cond
  ENCODER_TYPE: trajectron

DATA:
  DATASET_NAME: "univ_longer3"
  PREDICT_LENGTH: 15
  TRAJ:
    PRED_STATE: 'state_v'
    ACCEPT_NAN: True
    
SOLVER:
  USE_SCHEDULER: True
  WEIGHT_DECAY: 0.0