MODEL:
  TYPE: FlowChain_CIF_separate_cond
  FLOW:
    ARCHITECTURE: 'MAF'

DATA:
  DATASET_NAME: "simfork"
  TRAJ:
    PRED_STATE: 'state_v'
    
SOLVER:
  USE_SCHEDULER: True
  WEIGHT_DECAY: 0.0
  ITER: 500
  