MODEL:
  TYPE: FlowChain_separate_cond
  ENCODER_TYPE: trajectron
  FLOW:
    ARCHITECTURE: MAF

DATA:
  DATASET_NAME: "zara1"
  TP:
    PRED_STATE: 'state_v'
    ACCEPT_NAN: True
    
SOLVER:
  USE_SCHEDULER: True
  WEIGHT_DECAY: 0.0