MODEL:
  TYPE: FlowChain_separate
  ENCODER_TYPE: trajectron
  FLOW:
    ARCHITECTURE: MAF

DATA:
  DATASET_NAME: "eth"
  TRAJ:
    PRED_STATE: 'state_v'
    ACCEPT_NAN: True

SOLVER:
  USE_SCHEDULER: True
  WEIGHT_DECAY: 0.0